config/routes.rb
TiramizooCourierApp::Application.routes.draw do

  root :to => "main#index"

  resources :couriers, :only => [] do
    member do
      get :info
      post :state
      post :location
    end

    resources :deliveries, :only => [:index] do
      member do
        get :info
        post :state
      end
    end
  end

  match "location/nearby_couriers" => "couriers#nearby_couriers", :via => :get
  match "couriers/:courier_id/delivery_offers/:id/answer" => "deliveries#offer_answer", :via => :post

  resource :billings, :only => [:edit, :update]
  resource :settings, :only => [:edit, :update]

end

app/models/billing.rb
class Billing
  include VanillaModel

end

app/models/courier.rb
# Note: This class does not use ruby getter and setters because ruby setters cannot return an arbitrary value
# However, we want to return the result of the put/post request here
class Courier
  include TiramizooApi

  attr_accessor :id

  def authenticate
    @id = "1"
  end

  def get_info
    api_get "#{courier_path}/info"
  end

  def set_state(params)
    api_put "#{courier_path}/state", params
  end

  def set_location(params)
    api_put "#{courier_path}/location", params
  end

  def nearby_couriers
    api_get "location/nearby_couriers"
  end

  def get_delivery_info(params)
    api_get "#{courier_path}/deliveries/#{params[:id]}/info"
  end

  def set_delivery_state(params)
    api_put "#{courier_path}/deliveries/#{params[:id]}/state", params
  end

  def set_delivery_offer_answer(params)
    api_put "#{courier_path}/delivery_offers/#{params[:id]}/answer", params
  end

  protected
  def courier_path
    "couriers/#{id}"
  end

end

app/models/fake_courier.rb
class FakeCourier

  attr_accessor :id

  def authenticate
    @id = "1"
  end

  def get_info
    {
      id: "1",
      work_state: "not_available",
      travel_mode: "biking",
    }
  end

  def set_state(params)
    {work_state: "available"};
  end

  def set_location(params)
    {location: "nirvana"}
  end

  def nearby_couriers
    [
      {
        id: "1",
        position: {
          latitude: 48.14978,
          longitude:  11.57573
        },
        vehicle: "bike"
      },
      {
        id: "2",
        position: {
          latitude: 48.13899,
          longitude:  11.55010
        },
        vehicle: "car"
      },
      {
        id: "3",
        position: {
          latitude: 48.13857,
          longitude:  11.56576
        },
        vehicle: "car"
      },
      {
        id: "4",
        position: {
          latitude: 48.13307,
          longitude:  11.57463
        },
        vehicle: "motorbike"
      },
      {
        id: "5",
        position: {
          latitude: 48.14264,
          longitude:  11.57711
        },
        vehicle: "cargobike"
      },
      {
        id: "5",
        position: {
          latitude: 48.14264,
          longitude:  11.57711
        },
        vehicle: "cargobike"
      },
      {
        id: "6",
        position: {
          latitude: 48.14702,
          longitude:  11.58182
        },
        vehicle: "van"
      }
    ]
  end

  def get_delivery_info(id)
    {
      id: "1",
      state: "accepted",
      pop: {
        position: {
          latitude: 48.13307,
          longitude: 11.57463
        },
        address: {
          street: "Muellerstr. 42"
        },
        contact: 	{
          company_name: "tiramizoo",
          name: "Michael Loehr",
          phone: "089123456789"
        },
        notes: "Big box"
      },
      pod: {
        position: {
          latitude: 48.1498756,
          longitude: 11.5758714
        },
        address: {
          street: "Tuerkenstr. 60"
        },
        contact: {
          company_name: "tiramizoo",
          name: "Max Mustermann",
          phone: "089123456789"
        },
        notes: "Big box"
      }
    }
  end

  def set_delivery_state(params)
    case params[:state].to_sym
      when :picked_up
        get_result picked_up
      when :delivered
        get_result delivered
      else
        get_result
    end
  end

  def set_delivery_offer_answer(params)
    case params[:answer].to_sym
      when :accepted
        get_result accepted
      when :declined
        get_result
      else
        get_result
    end
  end

  protected
  def get_result(result = {})
    result[:status] = {
        code: "OK",
        message: "OK"}
    result
  end

  def accepted
    get_delivery_info(1)
  end

  def picked_up
    get_delivery_info(1)
  end

  def delivered
    get_delivery_info(1)
  end

end

app/models/settings.rb
class Settings
  include VanillaModel

  attr_accessor :username, :password

  def self.find
    
  end

end

app/models/tiramizoo_api.rb
module TiramizooApi
  
  module ClassMethods

    # refactor to use https://github.com/dbalatero/typhoeus instead of rest-client
    def call_api(method, path, params = {})
      rest_url = File.join(APP_CONFIG["tiramizoo_api_url"], "#{path}.json")
      case method
        when :get, :delete
          result = RestClient.send method, rest_url, :accept => :json
        else
          result = RestClient.send method, rest_url, params.to_json, :content_type => :json, :accept => :json
      end
      result
    end
    
  end

  def self.included(base)
    base.extend(ClassMethods)
  end

  def method_missing(id, *args, &block)
    case id.to_s
      when /^api_(.*)/
        y args
        self.class.call_api $1.to_sym, *args
      else
        super
    end
  end

end

app/models/vanilla_model.rb
module VanillaModel
  def self.included(base)
    base.class_eval do
        include ActiveModel::Validations
        include ActiveModel::Conversion
        extend ActiveModel::Naming

        def initialize(attributes = {})
          update_attributes attributes
        end
      
        def update_attributes(attributes)
          attributes.each do |name, value|
            send("#{name}=", value)
          end
        end

        def save
          if valid?
            #save
          else
            false
          end
        end

        def persisted?
          false
        end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate

  def authenticate
    @current_courier = FakeCourier.new
    @current_courier.authenticate
  end

  protected
  # jquery mobile "redirect" via rjs template
  def mobile_redirect_to(path)
    @mobile_redirect_path = path
    render "application/redirect"
  end

  def request_json
    HashWithIndifferentAccess.new(JSON.parse(request.body.read))
  end

end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController

  def edit
    #@current_delivery = @current_courier.get_info[:current_delivery]
  end

  def update
    mobile_redirect_to root_path
    #render :update do |page|
      #page.redirect_to root_url
    #end
  end

end

app/controllers/couriers_controller.rb
class CouriersController < ApplicationController

  def info
    render :json => @current_courier.get_info if request.get?
  end

  def state
    render :json => @current_courier.set_state(request_json) if request.post?
  end

  def location
    render :json => @current_courier.set_location(request_json) if request.post?
  end

  def nearby_couriers
    render :json => @current_courier.nearby_couriers if request.get?
  end

end

app/controllers/deliveries_controller.rb
class DeliveriesController < ApplicationController

  def index
    
  end

  def info
    render :json => @current_courier.get_delivery_info(request_json) if request.get?
  end

  def state
    render :json => @current_courier.set_delivery_state(request_json) if request.post?
  end

  def offer_answer
    render :json => @current_courier.set_delivery_offer_answer(request_json) if request.post?
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  layout "application"

  def index
    @courier_info = @current_courier.get_info
  end
  
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  def edit
    @settings = Settings.find()
  end

  def update
    #if @settings.update_attributes(params[:settings])
      #render :update do |page|
        #page.redirect_to root_url
      #end
    #end
    mobile_redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billings_helper.rb
module BillingsHelper

  def pop_street
    #@current_delivery[:pop][:address][:street]
    "<POP Street>"
  end

  def pod_street
    #@current_delivery[:pod][:address][:street]
    "<POD Street>"
  end

end

app/helpers/main_helper.rb
module MainHelper

  def courier_info_json
    @courier_info.to_json
  end

end

app/views/application/redirect.js.erb
(function () {
    var toPage = "<%= @mobile_redirect_path %>";
    if (toPage == "<%= root_path %>") {
       window.location.href = "#";
    } else {
       $.mobile.changePage(toPage, "slide", false, true);
    }
}());

app/views/billings/edit.html.haml
%div{"data-role" => "page"}
  %div{"data-role" => "header", "data-nobackbtn" => "true"}
    %h1 Billing
  %div{"data-role" => "content"}
    %form
      %table
        %th= "From #{pop_street} to #{pod_street}"
        %tr
          %td Base Price
          %td{"class" => "align-right"} 7,50 Euro
          %td
        %tr
          %td 15 min. Service Time at Pickup
          %td{"class" => "align-right"} 5,00 Euro
          %td
            = link_to "Change", "#", "data-role" => "button", "data-icon" => "check", "data-inline" => "true", "data-theme" => "a", "class" => "form-button-newline"
        %tr
          %td 10 min. Service Time at Dropoff
          %td{"class" => "align-right"} 3,00 Euro
          %td
            = link_to "Change", "#", "data-role" => "button", "data-icon" => "check", "data-inline" => "true", "data-theme" => "a", "class" => "form-button-newline"
        %tr
          %td{"class" => "strong"}
            %div{"data-role" => "fieldcontain"}
            %label{"for" => "base_price"} Total Price
          %td{"class" => "strong align-right"}
            %div{"data-role" => "fieldcontain"}
            %label{"for" => "base_price"} 15,50 Euro
          %td

      %fielset{"class" => "ui-grid-a"}
        %div{"class" => "ui-block-a"}
          = link_to "Send", "#", "data-role" => "button", "data-icon" => "check", "data-theme" => "a", "data-remote-url" => billings_path, :remote => true, :method => :put
        %div{"class" => "ui-block-b"}
          = link_to "Signature", "#", "data-role" => "button", "data-icon" => "check", "data-theme" => "a"

app/views/deliveries/index.html.haml
%div{"data-role" => "page"}
  %div{"data-role" => "header"}
    %h1 Deliveries
  %div{"data-role" => "content"}
    %form
    %div{"data-role" => "fieldcontain"}
      %label{"for" => "search"} Search:
      %input{"type" => "search", "name" => "search", "id" => "search"}
    %ul{"data-role" => "listview"}
      %li{"data-role" => "list-divider"} New Deliveries
      %li
        = link_to "Delivery1"
      %li
        = link_to "Delivery2"
      %li
        = link_to "Delivery3"
      %li{"data-role" => "list-divider"} In Progress
      %li
        = link_to "Delivery1"
      %li{"data-role" => "list-divider"} Completed Deliveries
      %li
        = link_to "Delivery1"
      %li
        = link_to "Delivery2"
      %li
        = link_to "Delivery3"
      %li
        = link_to "Delivery4"
      %li
        = link_to "Delivery5"

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
      %title tiramizoo
      %meta{"name" => "apple-mobile-web-app-capable", "content" => "yes"}
      %meta{"name" => "apple-mobile-web-app-status-bar-style", "content" => "black"}
      %link{"rel" => "apple-touch-icon", "href" => "images/apple-touch-icon.png"}
      = stylesheet_link_tag "jquery.mobile-1.0a3pre.min", "jquery.jgrowl", "application"
      = javascript_include_tag  "http://pubnub-prod.appspot.com/js-api?pub-key=demo&sub-key=demo&origin=pubsub.pubnub.com&ssl=&java=&devmode=1",
                                "http://maps.google.com/maps/api/js?sensor=true",
                                "https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js",
                                "jquery.jgrowl_compressed.js",
                                "json2",
                                "rails_mobile.js",
                                "test",                                 
                                "application",
                                "jquery.mobile-1.0a3pre.min"
      = yield :meta
      = csrf_meta_tag
    %body
      :javascript
        TIRAMIZOO.main.init({courierInfo: JSON.parse('#{courier_info_json}')});
      = yield

app/views/main/index.html.haml
%div{"data-role" => "page", "class" => "page-index"}
  %div{"data-role" => "content", "class" => "page-content"}
    #map-canvas{"class" => "map-canvas"}
  %div{"data-role" => "footer", "class" => "page-footer"}
    #main-nav{"class" => "main-nav", "data-role" => "navbar"}
      %ul
        %li
          = link_to "My Location", "#", "id" => "my-location", "data-icon" => "location"
        %li
          = link_to "Deliveries", courier_deliveries_path(@current_courier.id), "id" => "deliveries", "data-icon" => "deliveries"
        %li
          = link_to "", "#", "id" => "work-state", "data-icon" => "work-state"
        %li
          = link_to "Radar", "#", "id" => "radar", "data-icon" => "radar"
        %li
          = link_to "Settings", edit_settings_path, "id" => "settings", "data-icon" => "settings"

= javascript_include_tag "index"
:javascript
  $(document).ready(function() {
    TIRAMIZOO.index.init({courierInfo: JSON.parse('#{courier_info_json}'), defaultMenuItems: $("#main-nav ul:first")});
  });

app/views/settings/edit.html.haml
%div{"data-role" => "page"}
  %div{"data-role" => "header", "data-backbtn" => "false"}
    %h1 Settings
  %div{"data-role" => "content"}
    %form
      %div{"data-role" => "fieldcontain"}
        %label{"for" => "username"} Username:
        %input{"type" => "text", "name" => "username", "id" => "username", "data-theme" => "d"}

      %div{"data-role" => "fieldcontain"}
        %label{"for" => "username"} Password:
        %input{"type" => "text", "name" => "password", "id" => "password",  "data-theme" => "d"}

      %div{"data-role" => "fieldcontain", "class" => "ui-select-group"}
        %label{"for" => "vehicle"} Vehicle:
        %select{"name" => "vehicle", "id" => "vehicle", "data-theme" => "d"}
          %option{"value" => "bike"} Bike
          %option{"value" => "cargobike"} Cargobike
          %option{"value" => "motorbike"} Motorbike
          %option{"value" => "car"} Car
          %option{"value" => "van"} Van

      = link_to "Save", "#", "data-role" => "button", "data-icon" => "check", "data-theme" => "a", "data-remote-url" => settings_path, :remote => true, :method => :put